# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
loaderVersion="[55,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]]
modId="happytrails"
version="${file.jarVersion}"
displayName="Happy Trails Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/happy-trails"
updateJSONURL="https://github.com/mactso/happytrails/raw/main/update.json"
logoFile="HappyTrailsForgeMod.png"
authors="MacTso, Lupicus"
description='Happy Trails Mod.'
[[dependencies.happytrails]]
    modId="forge"
    mandatory=true
    versionRange="[55,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.happytrails]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="SERVER"
# side="BOTH", "CLIENT?", "SERVER"

